name: Backend Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version-of-node:
          - 14
          - 16
          - 18

    steps:
      - name: Repo Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version-of-node }}

      - name: Install Dependencies
        run: |
          cd Backend
          npm install

      - name: Checkpoint
        run: echo "Hello world, everything is working here"
