name: Backend Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: AWS_backend_deployment
    # strategy:
    #   matrix:
    #     version-of-node:
    #       - 14
    #       - 16
    #       - 18

    steps:
      - name: Repo Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3

      - name: Debug secrets
        run: |
          echo "Host: ${{ secrets.EC2_HOST }}"
          echo "User: ${{ secrets.EC2_USER }}"
          echo "Key: ${{ secrets.EC2_SSH_KEY }}"

      - name: Install Dependencies
        run: |
          cd Backend
          npm install

      - name: Checkpoint
        run: echo "Hello world, everything is working here"

      - name: Deploy via SSH on AWS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd BookVault
            git pull origin main
            echo "Deploying Backend"
            echo "${{ secrets.MONGO_URI }}" >> Backend/.env
            echo "${{ secrets.PORT }}" >> Backend/.env
            cd Backend
            docker build . -t backend2
            docker run -d -p 3000:3000 backend2
