name: Backend Deployment

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #     - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          cd Backend
          npm install

      - name: Checkpoint
        run: echo "Hello world, everything is working here"
