name: Backend Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    environment: AWS_backend_deployment
    # strategy:
    #   matrix:
    #     version-of-node:
    #       - 14
    #       - 16
    #       - 18

    steps:
      - name: Repo Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt install -y npm
          cd Backend
          npm install

      - name: Checkpoint
        run: echo "Hello world, everything is working here"

      - name: Run the application
        run: |
          cd Backend
          echo "Deploying Backend"
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          sudo apt install -y docker.io
          sudo docker build . -t backend3
          sudo docker run -d -p 3000:3000 backend3

      # - name: Deploy via SSH on AWS
      #   uses: appleboy/ssh-action@v1
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USER }}
      #     key: ${{ secrets.EC2_SSH_KEY }}
      #     port: 22
      #     script: |
      #       cd BookVault
      #       git pull origin main
      #       echo "Deploying Backend"
      #       echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> Backend/.env
      #       echo "PORT=${{ secrets.PORT }}" >> Backend/.env
      #       cd Backend
      #       docker build . -t backend2
      #       docker run -d -p 3000:3000 backend2
