name: Frontend Deployment

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install Dependencies
        run: |
          cd Frontend
          npm install

      - name: Build React application
        run: npm run build

      - name: Verify Build Output
        run: ls -la Frontend/build
